# Generated by Django 2.2 on 2019-04-25 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pregunta',
            old_name='Pregunta',
            new_name='Pregunta_Nombre',
        ),
        migrations.RenameField(
            model_name='seleccion',
            old_name='Seleccion',
            new_name='Seleccion_Nombre',
        ),
    ]
