# Generated by Django 2.2 on 2019-04-25 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0003_auto_20190425_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seleccion',
            old_name='votos',
            new_name='voto',
        ),
    ]
